apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-dev

images:
- name: ghcr.io/akuity/guestbook
  newName: ghcr.io/akuity/guestbook
  newTag: v0.0.1
